### ISSUE TITLE
Implement forgot-password

### ISSUE THREAD

**Issue by dgcnz** [pmariniutec/easyexam-frontend#125]

**Comment by mlovatonv** [comment]
I fixed a typo in the logout page name. We need to implement the forgot password workflow in the backend. This will consist in:

1. User enters his email in the forgot password page
2. EasyExam sends him an email with an unique url to reset his password (we need a reset password page)
3. User enters to the reset password page and changes his password
4. EasyExam updates his password and redirects him to the login page

**Comment by dgcnz** [comment]
Flow:
1. User enters email in the forgot password page
2. EasyExam sends him an email with a randomly generated password
3. User logs using such password
4. TODO: integrate backend's user PATCH for password: #144
