### ISSUE TITLE
Create exam page

### ISSUE THREAD

**Issue by martin-carrasco** [pmariniutec/easyexam-frontend#17]
Page where users can create an exam and at the same time rate questions for difficulty and correctnes and also write questions to obtain credits to add new questions to their exam.

- Should have a place where questions can be searched by tags (adding and removal of tags)
- Should have a place to write your own question if you choose to
- Should have a place to watch a preview of your exam
- Should have a place where suggested questions are shown with a way to rate them for difficulty and correctnes
- Should have a way to see your credit score (for getting new questions)
- Should have a popup that asks you to rate / post questions when you run out of credits

**Comment by mlovatonv** [comment]
Exam editor was created :)
